### ISSUE TITLE
Broken link on Custom App Page

### ISSUE THREAD

**Issue by JackZiyangChen** [spicetify/spicetify-docs#132]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.34.783
- Spicetify version: 2.36.3
```

### 📝 Description

https://spicetify.app/docs/development/custom-apps/
On this page, the `CustomApps folder` link is broken.

**Comment by JackZiyangChen** [comment]
Right. I was going update and say that, if I click around on the website and then access the Custom App page it works. But when I access the page through the link in discord, the link leads to a 404. Probably an issue with Docusaurus then.

**Comment by afonsojramos** [comment]
Should also have been fixed in #134 + #133 @JackZiyangChen, can you retry?

**Comment by JackZiyangChen** [comment]
Unfortunately I don't think the issue is resolved. It still gives me 404 when I try to access the same link when I opened the `custom app` page from discord.

**Comment by afonsojramos** [comment]
Alright, let's try again shall we? Think it might have been a mix of cloudflare + relative link vs absolute link. Can you check again?

**Comment by JackZiyangChen** [comment]
That's interesting. Seems like the issue is fixed. Thanks!
