### ISSUE TITLE
Mobile app

### ISSUE THREAD

**Issue by YashjitPal** [spicetify/spicetify-docs#87]
### 📝 Provide a description of the new feature

Please bring this thing to mobile. Most of the people are mostly comfortable with mobile and use mobile to use Spotify so it would be very nice to choose it to be implemented as a mobile app too.

### ➕ Additional Information

As there is no such apps that holds the ability to change the theme of Spotify to another level and those mouth watering features so it would be great to get such an app on mobile. Hope this get view. I'm anticipating a positive response from you.

**Comment by afonsojramos** [comment]
Sorry, but this is not within the scope of this project.
